export enum IcUrl {
  Soglasie = "soglasie",
  Rosgosstrah = "rosgosstrah",
  AlfaStrahovanie = "alfa-strahovanie",
  Sogaz = "sogaz",
  Renessans = "renessans",
  Maks = "maks",
  Ingosstrah = "ingosstrah",
  Reso = "reso-garantiya",
  Vsk = "vsk",
  Pari = "pari",
  Absolut = "absolyut-strahovanie",
  Tinkoff = "tinkoff-strahovanie",
  Guide = "guidehins",
  Gelios = "gelios",
  Ugoria = "ugoria",
  Astro = "astrovolga",
  Zetta = "zetta",
}

export enum CityUrl {
  Moskva = "moskva",
  Ekaterinburg = "ekaterinburg",
  SanktPeterburg = "sankt-peterburg",
  Novosibirsk = "novosibirsk",
  Samara = "samara",
  Orenburg = "orenburg",
  Kemerovo = "kemerovo",
  Voronezh = "voronezh",
  Krasnodar = "krasnodar",
  Ufa = "ufa",
  Chelyabinsk = "chelyabinsk",
  Kazan = "kazan",
  NizhnijNovgorod = "nizhnij_novgorod",
  Omsk = "omsk",
  Krasnoyarsk = "krasnoyarsk",
  Volgograd = "volgograd",
  Perm = "perm",
}

export enum ProgramUrl {
  Rosbank = "rosbank",
  Vtb = "vtb",
  AkBars = "akbars",
  MTS = "mts",
  Tinkoff = "tinkoff-bank",
  AlfaBank = "alfa-bank",
  Otkrytie = "bank-otkrytie",
  PochtaBank = "pochta-bank",
  HomeKreditBank = "home-kredit-bank",
  KreditEvropaBank = "kredit-evropa-bank",
  ATB = "atb",
  Sovkombank = "sovkombank",
  Ubrir = "ubrir",
  RenessansZhizn = "renessans-zhizn",
  Forabank = "fora-bank",
  Lokobank = "loko-bank",
  Metallinvestbank = "metallinvestbank",
  RenessansBank = "renessans-bank",
  CreditClub = "credit-club",
  Ekspobank = 'ekspobank',
  SanktPetersburg = 'sankt-petersburg',
  Uralsib = 'bank-uralsib',
  Banks = 'banks',
  DebitCard = 'debit-cards',
  CashLoan = 'cash-loan',
  BankDeposits = 'bank-deposits',
  Mortgage = 'mortgage',
  MFO = 'mfo',
}



